import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { ConfigProvider } from 'antd';
import theme from '@/lib/theme';
import StyledComponentsRegistry from '@/lib/AntdRegistry';
import { TooltipProvider } from '@/components/ui/tooltip';
import { AuthGuard } from '@/components/auth-guard';
import StoreProvider from '@/redux/StoreProvider';
import { Toaster } from '@/components/ui/toaster';
import { DatadogRum } from '@/components/datadog-rum';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <StyledComponentsRegistry>
            <ConfigProvider theme={theme}>
              <TooltipProvider>
                <DatadogRum />
                <AuthGuard>{children}</AuthGuard>
                <Toaster />
              </TooltipProvider>
            </ConfigProvider>
          </StyledComponentsRegistry>
        </StoreProvider>
      </body>
    </html>
  );
}
